### PR TITLE
Update gtld.json

### PR DESCRIPTION
**Pull request by dnsguru**
submitted for convenience for core contributors, the updated gtld list 
See issue #6

### CODE REVIEW

**Comment by pinheadmz** [comment]
Thank you so much for this information @dnsguru . Unfortunately this repo is used to generate hard-coded consensus parameters for handshake's mainnet, and that build process has already taken place and the output installed in hsd. The reserved name list is consensus code, and changing anything in it would mean a hard fork for the network. As such, changes to this repo are irrelevant, and we should develop solutions to this type of issue in hsd itself, specifically at the application layer. 

It's too late to stop any current auctions. A soft fork *could* be deployed to block new auctions on some names (they still would not be "reserved" the way google and apple are, but the miners can censor auctions for other names and prevent them from ever getting registered on HNS). This would require a supermajority of community support. 

Like I said in #6 if we want to give users the option to ignore certain data on the HNS blockchain, that can happen in the resolver. 

I really appreciate your attention and feedback on this. Please join us on irc freenode #handshake or on telegram: https://t.me/hns_tech to discuss further. 

I'm especially curious *WHEN* TLDs like `music` will be resolveable on the ICANN root zone.

**Comment by dnsguru** [comment]
@pinheadmz Thanks for the look - I am getting a lot of questions from existing TLDs on this one

> I'm especially curious WHEN TLDs like music will be resolveable on the ICANN root zone.

After the 2012 Round of Applications for new gTLDs like .MUSIC, and their subsequent review and delegation, these started entering the resolveable ICANN root zone in 2013.  The majority are delegated.

I think you specifically meant the ones in this ticket.  and .MUSIC specifically, is weeks/months away, after a decade and a half journey to the finish line.

**Comment by dnsguru** [comment]
Taking your guidance on this , @pinheadmz

**Comment by dnsguru** [comment]
Am leaving the branch for reference by future eyes

**Pull request closed without merging**
